/// Names accepted by the bundled Xray core (3115a981a8b6), not a newer engine.
/// https://github.com/patterniha/xray-core/blob/3115a981a8b6/transport/internet/tls/tls.go
const profileFingerprintPresets = [
  'chrome',
  'firefox',
  'safari',
  'ios',
  'android',
  'edge',
  '360',
  'qq',
  'random',
  'randomized',
  'randomizednoalpn',
  'unsafe',
];

const profileAdvancedFingerprints = [
  'hellofirefox_120',
  'hellofirefox_148',
  'hellochrome_120',
  'hellochrome_131',
  'hellochrome_133',
  'helloios_13',
  'helloios_14',
  'helloedge_106',
  'hellosafari_26_3',
  'hello360_11_0',
  'helloqq_11_1',
  'hellogolang',
  'hellorandomized',
  'hellorandomizedalpn',
  'hellorandomizednoalpn',
  'hellofirefox_auto',
  'hellofirefox_55',
  'hellofirefox_56',
  'hellofirefox_63',
  'hellofirefox_65',
  'hellofirefox_99',
  'hellofirefox_102',
  'hellofirefox_105',
  'hellochrome_auto',
  'hellochrome_58',
  'hellochrome_62',
  'hellochrome_70',
  'hellochrome_72',
  'hellochrome_83',
  'hellochrome_87',
  'hellochrome_96',
  'hellochrome_100',
  'hellochrome_102',
  'hellochrome_106_shuffle',
  'helloios_auto',
  'helloios_11_1',
  'helloios_12_1',
  'helloandroid_11_okhttp',
  'helloedge_85',
  'helloedge_auto',
  'hellosafari_16_0',
  'hellosafari_auto',
  'hello360_auto',
  'hello360_7_5',
  'helloqq_auto',
  'hellochrome_100_psk',
  'hellochrome_112_psk_shuf',
  'hellochrome_114_padding_psk_shuf',
  'hellochrome_115_pq',
  'hellochrome_115_pq_psk',
  'hellochrome_120_pq',
];

// The core accepts custom ALPN; these are v2rayNG's usual selections.
const profileAlpnChoices = ['h3', 'h2', 'http/1.1'];

// Go's non-insecure TLS <= 1.2 suites. TLS 1.3 suites cannot be overridden.
const profileCipherChoices = [
  'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256',
  'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384',
  'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256',
  'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384',
  'TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256',
  'TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256',
  'TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA',
  'TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA',
  'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA',
  'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA',
];
