import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('fa')];
  static const delegate = _AppStringsDelegate();

  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings)!;

  String text(String key) =>
      (_values[locale.languageCode] ?? _values['en']!)[key] ??
      _values['en']![key] ??
      key;

  static const _values = <String, Map<String, String>>{
    'en': {
      'home': 'Home',
      'servers': 'Servers',
      'settings': 'Settings',
      'logs': 'Logs',
      'selectedServer': 'Selected server',
      'noServer': 'No server available',
      'status': 'Connection status',
      'disconnected': 'Disconnected',
      'preparing': 'Preparing',
      'connecting': 'Connecting',
      'connected': 'Connected',
      'switching': 'Switching…',
      'reconnecting': 'Reconnecting',
      'stopping': 'Stopping',
      'error': 'Error',
      'publicIp': 'Public IP',
      'checking': 'Checking…',
      'unknown': 'Unknown',
      'subscription': 'Subscription',
      'used': 'Used',
      'remaining': 'Remaining',
      'unlimited': 'Unlimited',
      'expired': 'Expired',
      'expires': 'Expires',
      'connect': 'Connect',
      'disconnect': 'Disconnect',
      'ping': 'Ping',
      'subscriptionUsage': 'Subscription usage',
      'refresh': 'Update now',
      'notConfigured': 'Subscription endpoint is not configured.',
      'configureHint':
          'Set NIRANG_SUBSCRIPTION_URL in android/gradle.properties or the build environment.',
      'testAll': 'Test all',
      'cancel': 'Cancel',
      'testLatency': 'Test latency',
      'select': 'Select',
      'selected': 'Selected',
      'basicInfo': 'Basic information',
      'serverInformation': 'Server information',
      'serverActions': 'Server actions',
      'timeout': 'Timeout',
      'testing': 'Testing…',
      'neverTested': 'Not tested',
      'idle': 'Not tested',
      'success': 'Available',
      'protocol': 'Protocol',
      'transport': 'Transport',
      'routing': 'Routing',
      'dns': 'DNS',
      'name': 'Name',
      'security': 'Security',
      'country': 'Country',
      'port': 'Port',
      'generalInformation': 'General information',
      'protectedCredentials': 'Protected credentials',
      'credentialsProtected':
          'Sensitive values are intentionally masked and cannot be copied or changed.',
      'password': 'Password',
      'realityPublicKey': 'Reality public key',
      'shortId': 'Short ID',
      'delete': 'Delete',
      'deleteServer': 'Delete server?',
      'deleteServerBody':
          'This server will be hidden locally and will stay hidden after subscription updates.',
      'restoreDeletedServers': 'Restore deleted servers',
      'noDeletedServers': 'No locally deleted servers',
      'deletedServersCount': 'locally deleted server(s)',
      'serversRestored': 'Deleted servers restored',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'performanceMode': 'Performance Mode',
      'performanceModeSummary':
          'Reduce blur and heavy visual effects while keeping lightweight animations.',
      'language': 'Language',
      'english': 'English',
      'persian': 'فارسی',
      'global': 'Global proxy',
      'globalRoutingHint':
          'Send all non-DNS traffic through the selected proxy.',
      'bypassIran': 'Bypass Iran',
      'bypassIranHint':
          'Send .ir domains, Iran IP ranges, LAN and local destinations directly.',
      'custom': 'Custom routing',
      'customRuleHint': 'Listed domains and IP ranges connect directly.',
      'direct': 'Direct',
      'customDomains': 'Direct domains',
      'customIps': 'Direct IP / CIDR rules',
      'ruleHint': 'Comma or line separated rules',
      'save': 'Save',
      'apply': 'Apply',
      'requiredValue': 'A value is required.',
      'invalidDns': 'Enter a valid IP address or DNS hostname.',
      'invalidHttps': 'Enter a valid HTTPS URL.',
      'invalidRules': 'The rule text is invalid or too large.',
      'invalidPort': 'Enter a port from 1024 to 65535 (except 10809).',
      'invalidVpnAddress': 'Enter a private IPv4 interface address with CIDR.',
      'vpnSettings': 'VPN settings',
      'connectionMode': 'Connection mode',
      'vpn': 'VPN mode',
      'proxy': 'Proxy mode',
      'enableLocalDns': 'Enable local DNS',
      'enableLocalDnsSummary': 'Route DNS traffic through the Xray DNS module.',
      'enableFakeDns': 'Enable FakeDNS',
      'enableFakeDnsSummary': 'Use synthetic DNS results with Xray sniffing.',
      'vpnDns': 'VPN DNS',
      'vpnInterfaceAddress': 'VPN interface address',
      'localSocksPort': 'Local SOCKS port',
      'realPingConcurrency': 'Concurrent real-delay tests',
      'coreSettings': 'Core settings',
      'enableIpv6': 'Enable IPv6',
      'enableIpv6Summary':
          'Add an IPv6 address and route to the VPN interface.',
      'preferIpv6': 'Prefer IPv6',
      'preferIpv6Summary':
          'Prefer IPv6 when resolving the proxy server address.',
      'vpnMtu': 'VPN MTU',
      'vpnMtuSummary': 'Valid range: 1280–9000',
      'enableSniffing': 'Enable sniffing',
      'sniffingSummary':
          'Detect destination domains from HTTP, TLS and QUIC traffic.',
      'enableRouteOnly': 'Enable routeOnly',
      'routeOnlySummary':
          'Use sniffed domains for local routing without replacing the target address.',
      'remoteDns': 'Remote DNS',
      'domainStrategy': 'Domain strategy',
      'subscriptionUpdate': 'Subscription updates',
      'autoUpdate': 'Auto update',
      'updateInterval': 'Update interval',
      'lastUpdated': 'Last updated',
      'updates': 'Updates',
      'currentVersion': 'Current version',
      'checkForUpdates': 'Check for updates',
      'newVersionAvailable': 'New version available',
      'viewRelease': 'View release',
      'upToDate': "You're up to date.",
      'updateCheckFailed':
          'Could not reach GitHub. Check your connection and try again.',
      'performanceModeDialogBody':
          'If your device is older or the interface feels slow, Performance Mode can reduce visual effects and animations to improve responsiveness and battery usage.',
      'enable': 'Enable',
      'keepFullEffects': 'Keep full effects',
      'hours6': '6 hours',
      'hours12': '12 hours',
      'hours24': '24 hours',
      'never': 'Never',
      'telegram': 'Telegram channel',
      'telegramSubtitle': 'Updates, outages and server news',
      'joinTelegramTitle': 'Stay informed',
      'joinTelegramBody':
          'Join our Telegram channel to receive updates, outages and server news.',
      'joinTelegram': 'Join Telegram',
      'later': 'Later',
      'dontShowAgain': "Don't show again",
      'about': 'About',
      'coreVersion': 'Xray core',
      'packageName': 'Package ID',
      'noLogs': 'No logs yet',
      'clear': 'Clear',
      'clearLogs': 'Clear logs?',
      'clearLogsBody': 'This removes locally stored, redacted app events.',
      'operationFailed': 'Operation failed',
      'subscriptionUsageUnknown': 'Usage information unavailable',
      'serverCount': 'server(s)',
      'ipProvider': 'Current connection info test URL',
      'applyNextConnection': 'Changes apply on the next connection.',
      'emptyServers':
          'No supported VLESS, VMess or Trojan servers were loaded.',
    },
    'fa': {
      'home': 'خانه',
      'servers': 'سرورها',
      'settings': 'تنظیمات',
      'logs': 'گزارش‌ها',
      'selectedServer': 'سرور انتخاب‌شده',
      'noServer': 'سروری موجود نیست',
      'status': 'وضعیت اتصال',
      'disconnected': 'قطع',
      'preparing': 'در حال آماده‌سازی',
      'connecting': 'در حال اتصال',
      'connected': 'متصل',
      'switching': 'در حال تعویض سرور…',
      'reconnecting': 'اتصال مجدد',
      'stopping': 'در حال توقف',
      'error': 'خطا',
      'publicIp': 'آی‌پی عمومی',
      'checking': 'در حال بررسی…',
      'unknown': 'نامشخص',
      'subscription': 'اشتراک',
      'used': 'مصرف‌شده',
      'remaining': 'باقی‌مانده',
      'unlimited': 'نامحدود',
      'expired': 'منقضی‌شده',
      'expires': 'انقضا',
      'connect': 'اتصال',
      'disconnect': 'قطع اتصال',
      'ping': 'پینگ',
      'subscriptionUsage': 'مصرف اشتراک',
      'refresh': 'به‌روزرسانی اکنون',
      'notConfigured': 'آدرس داخلی اشتراک تنظیم نشده است.',
      'configureHint':
          'NIRANG_SUBSCRIPTION_URL را در android/gradle.properties یا محیط Build تنظیم کنید.',
      'testAll': 'تست همه',
      'cancel': 'لغو',
      'testLatency': 'تست تأخیر',
      'select': 'انتخاب',
      'selected': 'انتخاب‌شده',
      'basicInfo': 'اطلاعات پایه',
      'serverInformation': 'اطلاعات سرور',
      'serverActions': 'عملیات سرور',
      'timeout': 'پایان زمان',
      'testing': 'در حال تست…',
      'neverTested': 'تست نشده',
      'idle': 'تست نشده',
      'success': 'در دسترس',
      'protocol': 'پروتکل',
      'transport': 'انتقال',
      'routing': 'مسیریابی',
      'dns': 'DNS',
      'name': 'نام',
      'security': 'امنیت',
      'country': 'کشور',
      'port': 'پورت',
      'generalInformation': 'اطلاعات عمومی',
      'protectedCredentials': 'اطلاعات ورود محافظت‌شده',
      'credentialsProtected':
          'مقادیر حساس عمداً پوشانده شده‌اند و قابل کپی یا تغییر نیستند.',
      'password': 'رمز عبور',
      'realityPublicKey': 'کلید عمومی Reality',
      'shortId': 'شناسه کوتاه',
      'delete': 'حذف',
      'deleteServer': 'سرور حذف شود؟',
      'deleteServerBody':
          'این سرور به‌صورت محلی پنهان می‌شود و پس از به‌روزرسانی اشتراک نیز پنهان می‌ماند.',
      'restoreDeletedServers': 'بازیابی سرورهای حذف‌شده',
      'noDeletedServers': 'سرور حذف‌شده‌ای وجود ندارد',
      'deletedServersCount': 'سرور حذف‌شده محلی',
      'serversRestored': 'سرورهای حذف‌شده بازیابی شدند',
      'appearance': 'ظاهر',
      'theme': 'پوسته',
      'system': 'سیستم',
      'light': 'روشن',
      'dark': 'تیره',
      'performanceMode': 'حالت عملکرد',
      'performanceModeSummary':
          'کاهش محوشدگی و جلوه‌های سنگین با حفظ حرکت‌های سبک و روان.',
      'language': 'زبان',
      'english': 'English',
      'persian': 'فارسی',
      'global': 'پروکسی سراسری',
      'globalRoutingHint':
          'تمام ترافیک به‌جز DNS از پروکسی انتخاب‌شده عبور می‌کند.',
      'bypassIran': 'عبور مستقیم ایران',
      'bypassIranHint':
          'دامنه‌های ir، محدوده‌های IP ایران، شبکه محلی و مقصدهای محلی مستقیم متصل می‌شوند.',
      'custom': 'مسیریابی سفارشی',
      'customRuleHint': 'دامنه‌ها و محدوده‌های IP ثبت‌شده مستقیم متصل می‌شوند.',
      'direct': 'مستقیم',
      'customDomains': 'دامنه‌های مستقیم',
      'customIps': 'قواعد IP / CIDR مستقیم',
      'ruleHint': 'قواعد را با ویرگول یا خط جدید جدا کنید',
      'save': 'ذخیره',
      'apply': 'اعمال',
      'requiredValue': 'وارد کردن مقدار الزامی است.',
      'invalidDns': 'یک IP یا نام میزبان DNS معتبر وارد کنید.',
      'invalidHttps': 'یک آدرس HTTPS معتبر وارد کنید.',
      'invalidRules': 'متن قواعد نامعتبر یا بیش از حد بزرگ است.',
      'invalidPort': 'پورتی بین ۱۰۲۴ تا ۶۵۵۳۵ به‌جز ۱۰۸۰۹ وارد کنید.',
      'invalidVpnAddress': 'یک آدرس خصوصی IPv4 همراه CIDR وارد کنید.',
      'vpnSettings': 'تنظیمات VPN',
      'connectionMode': 'حالت اتصال',
      'vpn': 'حالت VPN',
      'proxy': 'حالت پروکسی',
      'enableLocalDns': 'فعال‌سازی DNS محلی',
      'enableLocalDnsSummary': 'ارسال ترافیک DNS به ماژول DNS هسته Xray.',
      'enableFakeDns': 'فعال‌سازی FakeDNS',
      'enableFakeDnsSummary': 'استفاده از پاسخ‌های مصنوعی DNS همراه Sniffing.',
      'vpnDns': 'DNS رابط VPN',
      'vpnInterfaceAddress': 'آدرس رابط VPN',
      'localSocksPort': 'پورت SOCKS محلی',
      'realPingConcurrency': 'تعداد تست هم‌زمان تأخیر واقعی',
      'coreSettings': 'تنظیمات هسته',
      'enableIpv6': 'فعال‌سازی IPv6',
      'enableIpv6Summary': 'افزودن آدرس و مسیر IPv6 به رابط VPN.',
      'preferIpv6': 'اولویت IPv6',
      'preferIpv6Summary': 'هنگام یافتن آدرس سرور پروکسی، IPv6 در اولویت باشد.',
      'vpnMtu': 'MTU شبکه VPN',
      'vpnMtuSummary': 'محدوده معتبر: ۱۲۸۰ تا ۹۰۰۰',
      'enableSniffing': 'فعال‌سازی Sniffing',
      'sniffingSummary': 'تشخیص دامنه مقصد از ترافیک HTTP، TLS و QUIC.',
      'enableRouteOnly': 'فعال‌سازی routeOnly',
      'routeOnlySummary':
          'استفاده از دامنه تشخیص‌داده‌شده فقط برای مسیریابی محلی.',
      'remoteDns': 'DNS راه‌دور',
      'domainStrategy': 'راهبرد دامنه',
      'subscriptionUpdate': 'به‌روزرسانی اشتراک',
      'autoUpdate': 'به‌روزرسانی خودکار',
      'updateInterval': 'فاصله به‌روزرسانی',
      'lastUpdated': 'آخرین به‌روزرسانی',
      'updates': 'به‌روزرسانی برنامه',
      'currentVersion': 'نسخه فعلی',
      'checkForUpdates': 'بررسی به‌روزرسانی',
      'newVersionAvailable': 'نسخه جدید موجود است',
      'viewRelease': 'مشاهده انتشار',
      'upToDate': 'برنامه به‌روز است.',
      'updateCheckFailed':
          'ارتباط با GitHub ممکن نشد. اتصال اینترنت را بررسی و دوباره تلاش کنید.',
      'performanceModeDialogBody':
          'اگر دستگاه شما قدیمی است یا رابط کاربری کند به نظر می‌رسد، حالت عملکرد با کاهش جلوه‌ها و حرکت‌ها پاسخ‌گویی و مصرف باتری را بهتر می‌کند.',
      'enable': 'فعال‌سازی',
      'keepFullEffects': 'حفظ جلوه‌های کامل',
      'hours6': '۶ ساعت',
      'hours12': '۱۲ ساعت',
      'hours24': '۲۴ ساعت',
      'never': 'هرگز',
      'telegram': 'کانال تلگرام',
      'telegramSubtitle': 'به‌روزرسانی‌ها، اختلال‌ها و اخبار سرورها',
      'joinTelegramTitle': 'از وضعیت سرویس باخبر بمانید',
      'joinTelegramBody':
          'برای دریافت به‌روزرسانی‌ها، اختلال‌ها و اخبار سرورها به کانال تلگرام ما بپیوندید.',
      'joinTelegram': 'عضویت در تلگرام',
      'later': 'بعداً',
      'dontShowAgain': 'دیگر نمایش نده',
      'about': 'درباره',
      'coreVersion': 'هسته Xray',
      'packageName': 'شناسه بسته',
      'noLogs': 'هنوز گزارشی وجود ندارد',
      'clear': 'پاک‌کردن',
      'clearLogs': 'گزارش‌ها پاک شوند؟',
      'clearLogsBody': 'رویدادهای محلی و پالایش‌شده برنامه حذف می‌شوند.',
      'operationFailed': 'عملیات ناموفق بود',
      'subscriptionUsageUnknown': 'اطلاعات مصرف در دسترس نیست',
      'serverCount': 'سرور',
      'ipProvider': 'آدرس بررسی اطلاعات اتصال فعلی',
      'applyNextConnection': 'تغییرات در اتصال بعدی اعمال می‌شوند.',
      'emptyServers': 'هیچ سرور VLESS، VMess یا Trojan معتبری بارگذاری نشد.',
    },
  };
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppStrings> load(Locale locale) =>
      SynchronousFuture(AppStrings(locale));

  @override
  bool shouldReload(_AppStringsDelegate old) => false;
}

extension AppStringsContext on BuildContext {
  String s(String key) => AppStrings.of(this).text(key);
}
